/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatInput: typeof import('./components/ChatInput.vue')['default']
    ChatInterface: typeof import('./components/ChatInterface.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    ChatSidebar: typeof import('./components/ChatSidebar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
